In [1]:
from nutils import*
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import colors, collections, cm
import vtk
import image_based_analysis as im

In [2]:
# Read mesh
fname = "data/flow_sim.vtu"
vtk_lumen_mesh = im.ReadVTKMesh(fname)
data = {"Traction", "normal"}
lumen_mesh = im.IM_TriMesh_CreateFromVTKMesh(vtk_lumen_mesh, data)

In [3]:
# Read in Autoplaque Image Data
fname = "data/autoplaque.mha"
autoplaque_img = im.IM_Image_CreateFromVTKMetaImageFile(fname)

In [4]:
# Read in Outer wall sdf Image Data
fname = "data/outer_wall.mha"
wallsdf_img = im.IM_Image_CreateFromVTKMetaImageFile(fname)

In [5]:
# Define material properties label maps
poisson_ratio_label_map = im.IM_LabelMap({-1 : 0, 75 : 0.27, 225 : .31, 33 : 0.27, 0 : 0.4})
youngs_modulus_label_map = im.IM_LabelMap({-1 : 2 / 1000, 75 : 1000 / 1000, 225 : 10000 / 1000, 33 : 100 / 1000, 0 : 60 / 1000})

In [6]:
# Build Meshes
shape = [10,10,10]
h = 3
origin = (39.35025102748692, -182.88678578819045, 635.1077093084257)

ns = function.Namespace()
ap_topo, geom = autoplaque_img.ToNutilsMesh(shape=shape)
a = origin - h * np.ones([3])
b = origin + h * np.ones([3])
aabb = im.IM_AABB(a, b)
topo, ns.x = aabb.ToNutilsMesh(shape)
lumen_mesh.TrimByAABB(aabb)
lumen_topo, lumen_geom = lumen_mesh.ToNutilsMesh()

In [7]:
bez = topo.sample('bezier', 2)
bez_proj = im.ProjectSampleTriMesh(ns.x, lumen_topo, lumen_geom, bez)

projecting point 1 / 8000
projecting point 2 / 8000
projecting point 3 / 8000
projecting point 4 / 8000
projecting point 5 / 8000
projecting point 6 / 8000
projecting point 7 / 8000
projecting point 8 / 8000
projecting point 9 / 8000
projecting point 10 / 8000
projecting point 11 / 8000
projecting point 12 / 8000
projecting point 13 / 8000
projecting point 14 / 8000
projecting point 15 / 8000
projecting point 16 / 8000
projecting point 17 / 8000
projecting point 18 / 8000
projecting point 19 / 8000
projecting point 20 / 8000
projecting point 21 / 8000
projecting point 22 / 8000
projecting point 23 / 8000
projecting point 24 / 8000
projecting point 25 / 8000
projecting point 26 / 8000
projecting point 27 / 8000
projecting point 28 / 8000
projecting point 29 / 8000
projecting point 30 / 8000
projecting point 31 / 8000
projecting point 32 / 8000
projecting point 33 / 8000
projecting point 34 / 8000
projecting point 35 / 8000
projecting point 36 / 8000
projecting point 37 / 8000
projecting

projecting point 299 / 8000
projecting point 300 / 8000
projecting point 301 / 8000
projecting point 302 / 8000
projecting point 303 / 8000
projecting point 304 / 8000
projecting point 305 / 8000
projecting point 306 / 8000
projecting point 307 / 8000
projecting point 308 / 8000
projecting point 309 / 8000
projecting point 310 / 8000
projecting point 311 / 8000
projecting point 312 / 8000
projecting point 313 / 8000
projecting point 314 / 8000
projecting point 315 / 8000
projecting point 316 / 8000
projecting point 317 / 8000
projecting point 318 / 8000
projecting point 319 / 8000
projecting point 320 / 8000
projecting point 321 / 8000
projecting point 322 / 8000
projecting point 323 / 8000
projecting point 324 / 8000
projecting point 325 / 8000
projecting point 326 / 8000
projecting point 327 / 8000
projecting point 328 / 8000
projecting point 329 / 8000
projecting point 330 / 8000
projecting point 331 / 8000
projecting point 332 / 8000
projecting point 333 / 8000
projecting point 334

projecting point 593 / 8000
projecting point 594 / 8000
projecting point 595 / 8000
projecting point 596 / 8000
projecting point 597 / 8000
projecting point 598 / 8000
projecting point 599 / 8000
projecting point 600 / 8000
projecting point 601 / 8000
projecting point 602 / 8000
projecting point 603 / 8000
projecting point 604 / 8000
projecting point 605 / 8000
projecting point 606 / 8000
projecting point 607 / 8000
projecting point 608 / 8000
projecting point 609 / 8000
projecting point 610 / 8000
projecting point 611 / 8000
projecting point 612 / 8000
projecting point 613 / 8000
projecting point 614 / 8000
projecting point 615 / 8000
projecting point 616 / 8000
projecting point 617 / 8000
projecting point 618 / 8000
projecting point 619 / 8000
projecting point 620 / 8000
projecting point 621 / 8000
projecting point 622 / 8000
projecting point 623 / 8000
projecting point 624 / 8000
projecting point 625 / 8000
projecting point 626 / 8000
projecting point 627 / 8000
projecting point 628

projecting point 887 / 8000
projecting point 888 / 8000
projecting point 889 / 8000
projecting point 890 / 8000
projecting point 891 / 8000
projecting point 892 / 8000
projecting point 893 / 8000
projecting point 894 / 8000
projecting point 895 / 8000
projecting point 896 / 8000
projecting point 897 / 8000
projecting point 898 / 8000
projecting point 899 / 8000
projecting point 900 / 8000
projecting point 901 / 8000
projecting point 902 / 8000
projecting point 903 / 8000
projecting point 904 / 8000
projecting point 905 / 8000
projecting point 906 / 8000
projecting point 907 / 8000
projecting point 908 / 8000
projecting point 909 / 8000
projecting point 910 / 8000
projecting point 911 / 8000
projecting point 912 / 8000
projecting point 913 / 8000
projecting point 914 / 8000
projecting point 915 / 8000
projecting point 916 / 8000
projecting point 917 / 8000
projecting point 918 / 8000
projecting point 919 / 8000
projecting point 920 / 8000
projecting point 921 / 8000
projecting point 922

projecting point 1175 / 8000
projecting point 1176 / 8000
projecting point 1177 / 8000
projecting point 1178 / 8000
projecting point 1179 / 8000
projecting point 1180 / 8000
projecting point 1181 / 8000
projecting point 1182 / 8000
projecting point 1183 / 8000
projecting point 1184 / 8000
projecting point 1185 / 8000
projecting point 1186 / 8000
projecting point 1187 / 8000
projecting point 1188 / 8000
projecting point 1189 / 8000
projecting point 1190 / 8000
projecting point 1191 / 8000
projecting point 1192 / 8000
projecting point 1193 / 8000
projecting point 1194 / 8000
projecting point 1195 / 8000
projecting point 1196 / 8000
projecting point 1197 / 8000
projecting point 1198 / 8000
projecting point 1199 / 8000
projecting point 1200 / 8000
projecting point 1201 / 8000
projecting point 1202 / 8000
projecting point 1203 / 8000
projecting point 1204 / 8000
projecting point 1205 / 8000
projecting point 1206 / 8000
projecting point 1207 / 8000
projecting point 1208 / 8000
projecting poi

projecting point 1459 / 8000
projecting point 1460 / 8000
projecting point 1461 / 8000
projecting point 1462 / 8000
projecting point 1463 / 8000
projecting point 1464 / 8000
projecting point 1465 / 8000
projecting point 1466 / 8000
projecting point 1467 / 8000
projecting point 1468 / 8000
projecting point 1469 / 8000
projecting point 1470 / 8000
projecting point 1471 / 8000
projecting point 1472 / 8000
projecting point 1473 / 8000
projecting point 1474 / 8000
projecting point 1475 / 8000
projecting point 1476 / 8000
projecting point 1477 / 8000
projecting point 1478 / 8000
projecting point 1479 / 8000
projecting point 1480 / 8000
projecting point 1481 / 8000
projecting point 1482 / 8000
projecting point 1483 / 8000
projecting point 1484 / 8000
projecting point 1485 / 8000
projecting point 1486 / 8000
projecting point 1487 / 8000
projecting point 1488 / 8000
projecting point 1489 / 8000
projecting point 1490 / 8000
projecting point 1491 / 8000
projecting point 1492 / 8000
projecting poi

projecting point 1743 / 8000
projecting point 1744 / 8000
projecting point 1745 / 8000
projecting point 1746 / 8000
projecting point 1747 / 8000
projecting point 1748 / 8000
projecting point 1749 / 8000
projecting point 1750 / 8000
projecting point 1751 / 8000
projecting point 1752 / 8000
projecting point 1753 / 8000
projecting point 1754 / 8000
projecting point 1755 / 8000
projecting point 1756 / 8000
projecting point 1757 / 8000
projecting point 1758 / 8000
projecting point 1759 / 8000
projecting point 1760 / 8000
projecting point 1761 / 8000
projecting point 1762 / 8000
projecting point 1763 / 8000
projecting point 1764 / 8000
projecting point 1765 / 8000
projecting point 1766 / 8000
projecting point 1767 / 8000
projecting point 1768 / 8000
projecting point 1769 / 8000
projecting point 1770 / 8000
projecting point 1771 / 8000
projecting point 1772 / 8000
projecting point 1773 / 8000
projecting point 1774 / 8000
projecting point 1775 / 8000
projecting point 1776 / 8000
projecting poi

projecting point 2027 / 8000
projecting point 2028 / 8000
projecting point 2029 / 8000
projecting point 2030 / 8000
projecting point 2031 / 8000
projecting point 2032 / 8000
projecting point 2033 / 8000
projecting point 2034 / 8000
projecting point 2035 / 8000
projecting point 2036 / 8000
projecting point 2037 / 8000
projecting point 2038 / 8000
projecting point 2039 / 8000
projecting point 2040 / 8000
projecting point 2041 / 8000
projecting point 2042 / 8000
projecting point 2043 / 8000
projecting point 2044 / 8000
projecting point 2045 / 8000
projecting point 2046 / 8000
projecting point 2047 / 8000
projecting point 2048 / 8000
projecting point 2049 / 8000
projecting point 2050 / 8000
projecting point 2051 / 8000
projecting point 2052 / 8000
projecting point 2053 / 8000
projecting point 2054 / 8000
projecting point 2055 / 8000
projecting point 2056 / 8000
projecting point 2057 / 8000
projecting point 2058 / 8000
projecting point 2059 / 8000
projecting point 2060 / 8000
projecting poi

projecting point 2311 / 8000
projecting point 2312 / 8000
projecting point 2313 / 8000
projecting point 2314 / 8000
projecting point 2315 / 8000
projecting point 2316 / 8000
projecting point 2317 / 8000
projecting point 2318 / 8000
projecting point 2319 / 8000
projecting point 2320 / 8000
projecting point 2321 / 8000
projecting point 2322 / 8000
projecting point 2323 / 8000
projecting point 2324 / 8000
projecting point 2325 / 8000
projecting point 2326 / 8000
projecting point 2327 / 8000
projecting point 2328 / 8000
projecting point 2329 / 8000
projecting point 2330 / 8000
projecting point 2331 / 8000
projecting point 2332 / 8000
projecting point 2333 / 8000
projecting point 2334 / 8000
projecting point 2335 / 8000
projecting point 2336 / 8000
projecting point 2337 / 8000
projecting point 2338 / 8000
projecting point 2339 / 8000
projecting point 2340 / 8000
projecting point 2341 / 8000
projecting point 2342 / 8000
projecting point 2343 / 8000
projecting point 2344 / 8000
projecting poi

projecting point 2594 / 8000
projecting point 2595 / 8000
projecting point 2596 / 8000
projecting point 2597 / 8000
projecting point 2598 / 8000
projecting point 2599 / 8000
projecting point 2600 / 8000
projecting point 2601 / 8000
projecting point 2602 / 8000
projecting point 2603 / 8000
projecting point 2604 / 8000
projecting point 2605 / 8000
projecting point 2606 / 8000
projecting point 2607 / 8000
projecting point 2608 / 8000
projecting point 2609 / 8000
projecting point 2610 / 8000
projecting point 2611 / 8000
projecting point 2612 / 8000
projecting point 2613 / 8000
projecting point 2614 / 8000
projecting point 2615 / 8000
projecting point 2616 / 8000
projecting point 2617 / 8000
projecting point 2618 / 8000
projecting point 2619 / 8000
projecting point 2620 / 8000
projecting point 2621 / 8000
projecting point 2622 / 8000
projecting point 2623 / 8000
projecting point 2624 / 8000
projecting point 2625 / 8000
projecting point 2626 / 8000
projecting point 2627 / 8000
projecting poi

projecting point 2878 / 8000
projecting point 2879 / 8000
projecting point 2880 / 8000
projecting point 2881 / 8000
projecting point 2882 / 8000
projecting point 2883 / 8000
projecting point 2884 / 8000
projecting point 2885 / 8000
projecting point 2886 / 8000
projecting point 2887 / 8000
projecting point 2888 / 8000
projecting point 2889 / 8000
projecting point 2890 / 8000
projecting point 2891 / 8000
projecting point 2892 / 8000
projecting point 2893 / 8000
projecting point 2894 / 8000
projecting point 2895 / 8000
projecting point 2896 / 8000
projecting point 2897 / 8000
projecting point 2898 / 8000
projecting point 2899 / 8000
projecting point 2900 / 8000
projecting point 2901 / 8000
projecting point 2902 / 8000
projecting point 2903 / 8000
projecting point 2904 / 8000
projecting point 2905 / 8000
projecting point 2906 / 8000
projecting point 2907 / 8000
projecting point 2908 / 8000
projecting point 2909 / 8000
projecting point 2910 / 8000
projecting point 2911 / 8000
projecting poi

projecting point 3162 / 8000
projecting point 3163 / 8000
projecting point 3164 / 8000
projecting point 3165 / 8000
projecting point 3166 / 8000
projecting point 3167 / 8000
projecting point 3168 / 8000
projecting point 3169 / 8000
projecting point 3170 / 8000
projecting point 3171 / 8000
projecting point 3172 / 8000
projecting point 3173 / 8000
projecting point 3174 / 8000
projecting point 3175 / 8000
projecting point 3176 / 8000
projecting point 3177 / 8000
projecting point 3178 / 8000
projecting point 3179 / 8000
projecting point 3180 / 8000
projecting point 3181 / 8000
projecting point 3182 / 8000
projecting point 3183 / 8000
projecting point 3184 / 8000
projecting point 3185 / 8000
projecting point 3186 / 8000
projecting point 3187 / 8000
projecting point 3188 / 8000
projecting point 3189 / 8000
projecting point 3190 / 8000
projecting point 3191 / 8000
projecting point 3192 / 8000
projecting point 3193 / 8000
projecting point 3194 / 8000
projecting point 3195 / 8000
projecting poi

projecting point 3446 / 8000
projecting point 3447 / 8000
projecting point 3448 / 8000
projecting point 3449 / 8000
projecting point 3450 / 8000
projecting point 3451 / 8000
projecting point 3452 / 8000
projecting point 3453 / 8000
projecting point 3454 / 8000
projecting point 3455 / 8000
projecting point 3456 / 8000
projecting point 3457 / 8000
projecting point 3458 / 8000
projecting point 3459 / 8000
projecting point 3460 / 8000
projecting point 3461 / 8000
projecting point 3462 / 8000
projecting point 3463 / 8000
projecting point 3464 / 8000
projecting point 3465 / 8000
projecting point 3466 / 8000
projecting point 3467 / 8000
projecting point 3468 / 8000
projecting point 3469 / 8000
projecting point 3470 / 8000
projecting point 3471 / 8000
projecting point 3472 / 8000
projecting point 3473 / 8000
projecting point 3474 / 8000
projecting point 3475 / 8000
projecting point 3476 / 8000
projecting point 3477 / 8000
projecting point 3478 / 8000
projecting point 3479 / 8000
projecting poi

projecting point 3730 / 8000
projecting point 3731 / 8000
projecting point 3732 / 8000
projecting point 3733 / 8000
projecting point 3734 / 8000
projecting point 3735 / 8000
projecting point 3736 / 8000
projecting point 3737 / 8000
projecting point 3738 / 8000
projecting point 3739 / 8000
projecting point 3740 / 8000
projecting point 3741 / 8000
projecting point 3742 / 8000
projecting point 3743 / 8000
projecting point 3744 / 8000
projecting point 3745 / 8000
projecting point 3746 / 8000
projecting point 3747 / 8000
projecting point 3748 / 8000
projecting point 3749 / 8000
projecting point 3750 / 8000
projecting point 3751 / 8000
projecting point 3752 / 8000
projecting point 3753 / 8000
projecting point 3754 / 8000
projecting point 3755 / 8000
projecting point 3756 / 8000
projecting point 3757 / 8000
projecting point 3758 / 8000
projecting point 3759 / 8000
projecting point 3760 / 8000
projecting point 3761 / 8000
projecting point 3762 / 8000
projecting point 3763 / 8000
projecting poi

projecting point 4014 / 8000
projecting point 4015 / 8000
projecting point 4016 / 8000
projecting point 4017 / 8000
projecting point 4018 / 8000
projecting point 4019 / 8000
projecting point 4020 / 8000
projecting point 4021 / 8000
projecting point 4022 / 8000
projecting point 4023 / 8000
projecting point 4024 / 8000
projecting point 4025 / 8000
projecting point 4026 / 8000
projecting point 4027 / 8000
projecting point 4028 / 8000
projecting point 4029 / 8000
projecting point 4030 / 8000
projecting point 4031 / 8000
projecting point 4032 / 8000
projecting point 4033 / 8000
projecting point 4034 / 8000
projecting point 4035 / 8000
projecting point 4036 / 8000
projecting point 4037 / 8000
projecting point 4038 / 8000
projecting point 4039 / 8000
projecting point 4040 / 8000
projecting point 4041 / 8000
projecting point 4042 / 8000
projecting point 4043 / 8000
projecting point 4044 / 8000
projecting point 4045 / 8000
projecting point 4046 / 8000
projecting point 4047 / 8000
projecting poi

projecting point 4298 / 8000
projecting point 4299 / 8000
projecting point 4300 / 8000
projecting point 4301 / 8000
projecting point 4302 / 8000
projecting point 4303 / 8000
projecting point 4304 / 8000
projecting point 4305 / 8000
projecting point 4306 / 8000
projecting point 4307 / 8000
projecting point 4308 / 8000
projecting point 4309 / 8000
projecting point 4310 / 8000
projecting point 4311 / 8000
projecting point 4312 / 8000
projecting point 4313 / 8000
projecting point 4314 / 8000
projecting point 4315 / 8000
projecting point 4316 / 8000
projecting point 4317 / 8000
projecting point 4318 / 8000
projecting point 4319 / 8000
projecting point 4320 / 8000
projecting point 4321 / 8000
projecting point 4322 / 8000
projecting point 4323 / 8000
projecting point 4324 / 8000
projecting point 4325 / 8000
projecting point 4326 / 8000
projecting point 4327 / 8000
projecting point 4328 / 8000
projecting point 4329 / 8000
projecting point 4330 / 8000
projecting point 4331 / 8000
projecting poi

projecting point 4582 / 8000
projecting point 4583 / 8000
projecting point 4584 / 8000
projecting point 4585 / 8000
projecting point 4586 / 8000
projecting point 4587 / 8000
projecting point 4588 / 8000
projecting point 4589 / 8000
projecting point 4590 / 8000
projecting point 4591 / 8000
projecting point 4592 / 8000
projecting point 4593 / 8000
projecting point 4594 / 8000
projecting point 4595 / 8000
projecting point 4596 / 8000
projecting point 4597 / 8000
projecting point 4598 / 8000
projecting point 4599 / 8000
projecting point 4600 / 8000
projecting point 4601 / 8000
projecting point 4602 / 8000
projecting point 4603 / 8000
projecting point 4604 / 8000
projecting point 4605 / 8000
projecting point 4606 / 8000
projecting point 4607 / 8000
projecting point 4608 / 8000
projecting point 4609 / 8000
projecting point 4610 / 8000
projecting point 4611 / 8000
projecting point 4612 / 8000
projecting point 4613 / 8000
projecting point 4614 / 8000
projecting point 4615 / 8000
projecting poi

projecting point 4866 / 8000
projecting point 4867 / 8000
projecting point 4868 / 8000
projecting point 4869 / 8000
projecting point 4870 / 8000
projecting point 4871 / 8000
projecting point 4872 / 8000
projecting point 4873 / 8000
projecting point 4874 / 8000
projecting point 4875 / 8000
projecting point 4876 / 8000
projecting point 4877 / 8000
projecting point 4878 / 8000
projecting point 4879 / 8000
projecting point 4880 / 8000
projecting point 4881 / 8000
projecting point 4882 / 8000
projecting point 4883 / 8000
projecting point 4884 / 8000
projecting point 4885 / 8000
projecting point 4886 / 8000
projecting point 4887 / 8000
projecting point 4888 / 8000
projecting point 4889 / 8000
projecting point 4890 / 8000
projecting point 4891 / 8000
projecting point 4892 / 8000
projecting point 4893 / 8000
projecting point 4894 / 8000
projecting point 4895 / 8000
projecting point 4896 / 8000
projecting point 4897 / 8000
projecting point 4898 / 8000
projecting point 4899 / 8000
projecting poi

projecting point 5150 / 8000
projecting point 5151 / 8000
projecting point 5152 / 8000
projecting point 5153 / 8000
projecting point 5154 / 8000
projecting point 5155 / 8000
projecting point 5156 / 8000
projecting point 5157 / 8000
projecting point 5158 / 8000
projecting point 5159 / 8000
projecting point 5160 / 8000
projecting point 5161 / 8000
projecting point 5162 / 8000
projecting point 5163 / 8000
projecting point 5164 / 8000
projecting point 5165 / 8000
projecting point 5166 / 8000
projecting point 5167 / 8000
projecting point 5168 / 8000
projecting point 5169 / 8000
projecting point 5170 / 8000
projecting point 5171 / 8000
projecting point 5172 / 8000
projecting point 5173 / 8000
projecting point 5174 / 8000
projecting point 5175 / 8000
projecting point 5176 / 8000
projecting point 5177 / 8000
projecting point 5178 / 8000
projecting point 5179 / 8000
projecting point 5180 / 8000
projecting point 5181 / 8000
projecting point 5182 / 8000
projecting point 5183 / 8000
projecting poi

projecting point 5434 / 8000
projecting point 5435 / 8000
projecting point 5436 / 8000
projecting point 5437 / 8000
projecting point 5438 / 8000
projecting point 5439 / 8000
projecting point 5440 / 8000
projecting point 5441 / 8000
projecting point 5442 / 8000
projecting point 5443 / 8000
projecting point 5444 / 8000
projecting point 5445 / 8000
projecting point 5446 / 8000
projecting point 5447 / 8000
projecting point 5448 / 8000
projecting point 5449 / 8000
projecting point 5450 / 8000
projecting point 5451 / 8000
projecting point 5452 / 8000
projecting point 5453 / 8000
projecting point 5454 / 8000
projecting point 5455 / 8000
projecting point 5456 / 8000
projecting point 5457 / 8000
projecting point 5458 / 8000
projecting point 5459 / 8000
projecting point 5460 / 8000
projecting point 5461 / 8000
projecting point 5462 / 8000
projecting point 5463 / 8000
projecting point 5464 / 8000
projecting point 5465 / 8000
projecting point 5466 / 8000
projecting point 5467 / 8000
projecting poi

projecting point 5718 / 8000
projecting point 5719 / 8000
projecting point 5720 / 8000
projecting point 5721 / 8000
projecting point 5722 / 8000
projecting point 5723 / 8000
projecting point 5724 / 8000
projecting point 5725 / 8000
projecting point 5726 / 8000
projecting point 5727 / 8000
projecting point 5728 / 8000
projecting point 5729 / 8000
projecting point 5730 / 8000
projecting point 5731 / 8000
projecting point 5732 / 8000
projecting point 5733 / 8000
projecting point 5734 / 8000
projecting point 5735 / 8000
projecting point 5736 / 8000
projecting point 5737 / 8000
projecting point 5738 / 8000
projecting point 5739 / 8000
projecting point 5740 / 8000
projecting point 5741 / 8000
projecting point 5742 / 8000
projecting point 5743 / 8000
projecting point 5744 / 8000
projecting point 5745 / 8000
projecting point 5746 / 8000
projecting point 5747 / 8000
projecting point 5748 / 8000
projecting point 5749 / 8000
projecting point 5750 / 8000
projecting point 5751 / 8000
projecting poi

projecting point 6002 / 8000
projecting point 6003 / 8000
projecting point 6004 / 8000
projecting point 6005 / 8000
projecting point 6006 / 8000
projecting point 6007 / 8000
projecting point 6008 / 8000
projecting point 6009 / 8000
projecting point 6010 / 8000
projecting point 6011 / 8000
projecting point 6012 / 8000
projecting point 6013 / 8000
projecting point 6014 / 8000
projecting point 6015 / 8000
projecting point 6016 / 8000
projecting point 6017 / 8000
projecting point 6018 / 8000
projecting point 6019 / 8000
projecting point 6020 / 8000
projecting point 6021 / 8000
projecting point 6022 / 8000
projecting point 6023 / 8000
projecting point 6024 / 8000
projecting point 6025 / 8000
projecting point 6026 / 8000
projecting point 6027 / 8000
projecting point 6028 / 8000
projecting point 6029 / 8000
projecting point 6030 / 8000
projecting point 6031 / 8000
projecting point 6032 / 8000
projecting point 6033 / 8000
projecting point 6034 / 8000
projecting point 6035 / 8000
projecting poi

projecting point 6286 / 8000
projecting point 6287 / 8000
projecting point 6288 / 8000
projecting point 6289 / 8000
projecting point 6290 / 8000
projecting point 6291 / 8000
projecting point 6292 / 8000
projecting point 6293 / 8000
projecting point 6294 / 8000
projecting point 6295 / 8000
projecting point 6296 / 8000
projecting point 6297 / 8000
projecting point 6298 / 8000
projecting point 6299 / 8000
projecting point 6300 / 8000
projecting point 6301 / 8000
projecting point 6302 / 8000
projecting point 6303 / 8000
projecting point 6304 / 8000
projecting point 6305 / 8000
projecting point 6306 / 8000
projecting point 6307 / 8000
projecting point 6308 / 8000
projecting point 6309 / 8000
projecting point 6310 / 8000
projecting point 6311 / 8000
projecting point 6312 / 8000
projecting point 6313 / 8000
projecting point 6314 / 8000
projecting point 6315 / 8000
projecting point 6316 / 8000
projecting point 6317 / 8000
projecting point 6318 / 8000
projecting point 6319 / 8000
projecting poi

projecting point 6570 / 8000
projecting point 6571 / 8000
projecting point 6572 / 8000
projecting point 6573 / 8000
projecting point 6574 / 8000
projecting point 6575 / 8000
projecting point 6576 / 8000
projecting point 6577 / 8000
projecting point 6578 / 8000
projecting point 6579 / 8000
projecting point 6580 / 8000
projecting point 6581 / 8000
projecting point 6582 / 8000
projecting point 6583 / 8000
projecting point 6584 / 8000
projecting point 6585 / 8000
projecting point 6586 / 8000
projecting point 6587 / 8000
projecting point 6588 / 8000
projecting point 6589 / 8000
projecting point 6590 / 8000
projecting point 6591 / 8000
projecting point 6592 / 8000
projecting point 6593 / 8000
projecting point 6594 / 8000
projecting point 6595 / 8000
projecting point 6596 / 8000
projecting point 6597 / 8000
projecting point 6598 / 8000
projecting point 6599 / 8000
projecting point 6600 / 8000
projecting point 6601 / 8000
projecting point 6602 / 8000
projecting point 6603 / 8000
projecting poi

projecting point 6854 / 8000
projecting point 6855 / 8000
projecting point 6856 / 8000
projecting point 6857 / 8000
projecting point 6858 / 8000
projecting point 6859 / 8000
projecting point 6860 / 8000
projecting point 6861 / 8000
projecting point 6862 / 8000
projecting point 6863 / 8000
projecting point 6864 / 8000
projecting point 6865 / 8000
projecting point 6866 / 8000
projecting point 6867 / 8000
projecting point 6868 / 8000
projecting point 6869 / 8000
projecting point 6870 / 8000
projecting point 6871 / 8000
projecting point 6872 / 8000
projecting point 6873 / 8000
projecting point 6874 / 8000
projecting point 6875 / 8000
projecting point 6876 / 8000
projecting point 6877 / 8000
projecting point 6878 / 8000
projecting point 6879 / 8000
projecting point 6880 / 8000
projecting point 6881 / 8000
projecting point 6882 / 8000
projecting point 6883 / 8000
projecting point 6884 / 8000
projecting point 6885 / 8000
projecting point 6886 / 8000
projecting point 6887 / 8000
projecting poi

projecting point 7138 / 8000
projecting point 7139 / 8000
projecting point 7140 / 8000
projecting point 7141 / 8000
projecting point 7142 / 8000
projecting point 7143 / 8000
projecting point 7144 / 8000
projecting point 7145 / 8000
projecting point 7146 / 8000
projecting point 7147 / 8000
projecting point 7148 / 8000
projecting point 7149 / 8000
projecting point 7150 / 8000
projecting point 7151 / 8000
projecting point 7152 / 8000
projecting point 7153 / 8000
projecting point 7154 / 8000
projecting point 7155 / 8000
projecting point 7156 / 8000
projecting point 7157 / 8000
projecting point 7158 / 8000
projecting point 7159 / 8000
projecting point 7160 / 8000
projecting point 7161 / 8000
projecting point 7162 / 8000
projecting point 7163 / 8000
projecting point 7164 / 8000
projecting point 7165 / 8000
projecting point 7166 / 8000
projecting point 7167 / 8000
projecting point 7168 / 8000
projecting point 7169 / 8000
projecting point 7170 / 8000
projecting point 7171 / 8000
projecting poi

projecting point 7422 / 8000
projecting point 7423 / 8000
projecting point 7424 / 8000
projecting point 7425 / 8000
projecting point 7426 / 8000
projecting point 7427 / 8000
projecting point 7428 / 8000
projecting point 7429 / 8000
projecting point 7430 / 8000
projecting point 7431 / 8000
projecting point 7432 / 8000
projecting point 7433 / 8000
projecting point 7434 / 8000
projecting point 7435 / 8000
projecting point 7436 / 8000
projecting point 7437 / 8000
projecting point 7438 / 8000
projecting point 7439 / 8000
projecting point 7440 / 8000
projecting point 7441 / 8000
projecting point 7442 / 8000
projecting point 7443 / 8000
projecting point 7444 / 8000
projecting point 7445 / 8000
projecting point 7446 / 8000
projecting point 7447 / 8000
projecting point 7448 / 8000
projecting point 7449 / 8000
projecting point 7450 / 8000
projecting point 7451 / 8000
projecting point 7452 / 8000
projecting point 7453 / 8000
projecting point 7454 / 8000
projecting point 7455 / 8000
projecting poi

projecting point 7706 / 8000
projecting point 7707 / 8000
projecting point 7708 / 8000
projecting point 7709 / 8000
projecting point 7710 / 8000
projecting point 7711 / 8000
projecting point 7712 / 8000
projecting point 7713 / 8000
projecting point 7714 / 8000
projecting point 7715 / 8000
projecting point 7716 / 8000
projecting point 7717 / 8000
projecting point 7718 / 8000
projecting point 7719 / 8000
projecting point 7720 / 8000
projecting point 7721 / 8000
projecting point 7722 / 8000
projecting point 7723 / 8000
projecting point 7724 / 8000
projecting point 7725 / 8000
projecting point 7726 / 8000
projecting point 7727 / 8000
projecting point 7728 / 8000
projecting point 7729 / 8000
projecting point 7730 / 8000
projecting point 7731 / 8000
projecting point 7732 / 8000
projecting point 7733 / 8000
projecting point 7734 / 8000
projecting point 7735 / 8000
projecting point 7736 / 8000
projecting point 7737 / 8000
projecting point 7738 / 8000
projecting point 7739 / 8000
projecting poi

projecting point 7990 / 8000
projecting point 7991 / 8000
projecting point 7992 / 8000
projecting point 7993 / 8000
projecting point 7994 / 8000
projecting point 7995 / 8000
projecting point 7996 / 8000
projecting point 7997 / 8000
projecting point 7998 / 8000
projecting point 7999 / 8000
projecting point 8000 / 8000


In [9]:
ns.linbasis = lumen_topo.basis('spline',1)
normals = lumen_mesh.GetData("normal")
ns.Nx = ns.linbasis.dot(normals[:,0])
ns.Ny = ns.linbasis.dot(normals[:,1])
ns.Nz = ns.linbasis.dot(normals[:,2])
ns.n_i = '<Nx, Ny, Nz>_i'
ns.N = bez.asfunction(bez_proj.eval(ns.n))

In [10]:
ns.Px = bez.asfunction(bez_proj.eval(lumen_geom))
ns.u_i = 'x_i - Px_i'
ns.dist = 'sqrt(u_i u_i)'
ns.d = 'u_i N_i'
ns.I = 'sign(d)'
ns.sdf = 'I dist'

In [11]:
vals = bez.eval(ns.sdf)
xvals = bez.eval(ns.x)
distvals = bez.eval(ns.dist)
Ivals = bez.eval(ns.I)
nvals = bez.eval(ns.N)

In [12]:
export.vtk("test_3d_mat_props", bez.tri, xvals, vals=vals, dist=distvals, Ivals=Ivals, nvals=nvals)

test_3d_mat_props.vtk


In [7]:
rand = im.CreateRandomSample(ap_topo, 1)
rand_proj = im.ProjectSampleTriMesh(ns.x, lumen_topo, lumen_geom, rand)
ns.D = im.DistancePointTriMesh(lumen_mesh, ns.x[0], ns.x[1], ns.x[2])

projecting point 1 / 1


In [8]:
# Test projection
pt = rand.eval(ns.x)
print(pt)
pt_proj = rand_proj.eval(lumen_geom)
print(pt_proj)

[[  38.3698624  -183.74341279  636.7126755 ]]
[[  39.20769512 -183.47859444  635.53979453]]


In [9]:
# Test projection
dist = im.ProjectPointOntoTriMesh(lumen_mesh.verts, lumen_mesh.tris, pt[0])
print(dist)

(739, (array([0.37873825, 0.62126175, 0.        ]), array([  39.20906188, -183.40413668,  635.56531498])))


In [18]:
# pick a triangle
i = 0
tri = lumen_mesh.tris[i]
verts = np.array([lumen_mesh.verts[j] for j in tri])
print(verts)

[[  40.10909271 -185.22671509  635.50738525]
 [  40.15038582 -185.29454278  635.42578672]
 [  40.21168518 -185.38978577  635.49822998]]


In [25]:
p = np.array([39.425234, -185.768064, 635.500755])
proj = im.ProjectPointOntoTriangle(p, verts[0], verts[1], verts[2])
dist = np.linalg.norm(p - proj[1])
dist2 = im.DistancePointTriangle(p, verts[0], verts[1], verts[2])
print(pt[0])
print(proj)
print(dist)
print(dist2)

[  42.10660396 -181.41113212  635.63794603]
(array([0.4002693 , 0.19523352, 0.40449718]), array([  40.15865287, -185.30591896,  635.4877512 ]))
0.8669777303988461
0.8681263398393484


test_3d_mat_props.vtk


In [13]:
s = lumen_topo.sample('bezier',2)
xvals = s.eval(lumen_geom)
nvals = s.eval(ns.n)
export.vtk("trimmed_lumen", s.tri, xvals,nvals=nvals)

trimmed_lumen.vtk


In [31]:
class ArrayWrapper:
    def __init__(self, array):
        self.array = array
        
class UdotV(function.Array):
    @types.apply_annotations
    def __init__(self, wrapped_array, *args:function.asarrays):
        self.array = wrapped_array.array
        shapes = set(arg.shape for arg in args)
        assert len(shapes) == 1, 'pointwise arguments have inconsistent shapes'
        shape, = shapes
        self.args = args
        super().__init__(args=args, shape=shape, dtype=np.float64)
    
    def evalf(self, x, y, z):
        return np.array([ x[i] * self.array[i][0] + y[i] * self.array[i][1] + z[i] * self.array[i][2] for i in range(len(x))])
    
    def _derivative(self, var, seen):
        return np.zeros(self.shape + var.shape)

In [6]:
p = np.array([1,-0.2,0.1])
p1 = np.array([0,0,1])
p2 = np.array([0,0,0])
p3 = np.array([0,1,0])
xi, proj = im.ProjectPointOntoTriangle(p, p1, p2, p3)
print(xi)
print(proj)

[0.1 1.  0. ]
[0.  0.  0.1]


In [37]:

print(bez.eval(ns.normal))
print(normals)

[[ 0.72622501  0.01783705 -0.68722563]
 [-0.51104814 -0.22304845  0.83010794]
 [ 0.55318048  0.34645299 -0.75760259]
 ...
 [-0.3058192  -0.00717277  0.95206259]
 [ 0.40502901 -0.42748515 -0.80821281]
 [ 0.47248202 -0.08181152 -0.87753497]]
[[ 0.72622501  0.01783705 -0.68722563]
 [-0.51104814 -0.22304845  0.83010794]
 [ 0.55318048  0.34645299 -0.75760259]
 ...
 [-0.3058192  -0.00717277  0.95206259]
 [ 0.40502901 -0.42748515 -0.80821281]
 [ 0.47248202 -0.08181152 -0.87753497]]


In [22]:
print(aabb.ptB - aabb.ptA)
print(bez.eval(ns.x))

[6. 6. 6.]
[[ -84.7695    -288.27       505.275    ]
 [ -84.7695    -288.27       521.875996 ]
 [ -84.7695    -264.6699744  505.275    ]
 ...
 [ 151.230756   -75.8697696  671.28496  ]
 [ 151.230756   -52.269744   654.683964 ]
 [ 151.230756   -52.269744   671.28496  ]]


In [15]:
print(bez_proj.points[0])

CoordsPoints([[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]])


In [13]:
a = im.IM_LabelMap( {"hey" : 1, "you" : 2} )
b = im.IM_LabelMap( {0 : 1, 1 : 2} )
a.Remap(b.map.keys())
print(a.map)

{0: 1, 1: 2}


In [10]:
outpath = "trimmed_lumen_mesh.stl"
fpath = "C:\\Users\\Mike\\Documents\\MJJ\\Heartflow\\heartflow\\Model_00_slice_00\\trimmed_lumen-2.vtk"
im.ConvertVTKToSTL(fpath, outpath)

TypeError: SetInputConnection argument %Id: %V

[  36.35025103 -185.88678579  632.10770931]
[  42.35025103 -179.88678579  638.10770931]


In [14]:
print(bez)

_DefaultIndex((<nutils.transformseq.StructuredTransforms object at 0x0000029DBB7CF948>,),_Uniform(TensorPoints(SimplexBezierPoints(1,2),TensorPoints(SimplexBezierPoints(1,2),SimplexBezierPoints(1,2))),1000))


In [17]:
a = {1: 2, 3 : 4}
print(a.keys())
b = a.values()
for asdf in b:
    print(asdf)

dict_keys([1, 3])
2
4
