In [2]:
import image_based_analysis as im
from nutils import*
import numpy as np

In [2]:
# Create a VTK Mesh
fname = "data/flow_sim.vtu"
lumen_mesh = im.VTKTriMesh(fname)

In [3]:
# Get VTK Mesh data arrays
verts = lumen_mesh.GetPoints()
cells = lumen_mesh.GetCells()
tractions = lumen_mesh.GetData("Traction")

print("verts : " + str(verts))
print("cells : " + str(cells))
print("tractions : " + str(tractions))

verts : [[  42.45257187 -197.14161682  638.48364258]
 [  42.40272522 -196.73388672  637.65594482]
 [  42.34238434 -196.76712036  637.72344971]
 ...
 [ -26.75434532 -219.60407872  588.20773684]
 [ -26.92930987 -219.58942657  588.32584456]
 [ -26.99084054 -219.78499199  588.51420468]]
cells : [[    2     1    38]
 [    2    38    39]
 [   39    38    40]
 ...
 [91722 91659 91622]
 [91557 91716 91555]
 [91716 91557 91585]]
tractions : [[-3125.97331401 -3367.17938047  3839.26300608]
 [-3795.25603839  -219.16613784 -5071.03131908]
 [-4703.8847161   -995.31466902 -4506.36114468]
 ...
 [    0.             0.             0.        ]
 [    0.             0.             0.        ]
 [    0.             0.             0.        ]]


In [4]:
# Build Nutils mesh from VTK mesh
topo, geom = lumen_mesh.ToNutilsMesh()

In [5]:
# Create MetaImage
fname = "data/outer_wall.mha"
img = im.MetaImage(fname)

In [6]:
# Get MetaImage data
origin = img.GetOrigin()
spacing = img.GetSpacing()
shape = img.GetShape()
vals = img.GetValues()

print("origin : " + str(origin))
print("spacing : " + str(spacing))
print("shape : " + str(shape))
print("vals : " + str(vals))

origin : [ -32.75 -243.    543.5 ]
spacing : [0.25 0.25 0.25]
shape : [502 442 411]
vals : [0. 0. 0. ... 0. 0. 0.]


In [7]:
# Create Nutils mesh on Meta Image
shape = [20,20,20]
topo, geom = img.ToNutilsMesh(shape)

In [8]:
# Create a Voxel Image Function
ns = function.Namespace()
ns.f = im.VoxelImageFunction(img, geom[0], geom[1], geom[2])

In [9]:
# Write vtk
n = 5
im.WriteVTK(topo, geom, {"f" : ns.f}, n, "test")

test.vtk


In [12]:
np.minimum([1,0,1],[0,1,0])

array([0, 0, 0])

In [6]:
a = np.array([1,0,0])
b = np.array([0,1,0])
np.cross(a,b)

array([0, 0, 1])