In [1]:
from nutils import*
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import colors, collections, cm
import vtk
import image_based_analysis as im

In [2]:
def BuildGridMesh(ptA, ptB, shape):
    x = [np.linspace(xmin,xmax,nelems+1) for xmin,xmax,nelems in zip(ptA,ptB,shape)]
    return mesh.rectilinear(x)


In [14]:
topo, geom = BuildGridMesh([0,0,0],[1,1,1],[2,2,2])

In [15]:
bez = topo.sample('bezier',2)
gauss = topo.sample('gauss',2)

In [58]:
print(gauss.points.npoints)

64


In [41]:
WriteSample(bez,None,None)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[[[0. 0. 0.]
  [0. 0. 1.]
  [0. 1. 0.]
  [0. 1. 1.]
  [1. 0. 0.]
  [1. 0. 1.]
  [1. 1. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 1.]
  [0. 1. 0.]
  [0. 1. 1.]
  [1. 0. 0.]
  [1. 0. 1.]
  [1. 1. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 1.]
  [0. 1. 0.]
  [0. 1. 1.]
  [1. 0. 0.]
  [1. 0. 1.]
  [1. 1. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 1.]
  [0. 1. 0.]
  [0. 1. 1.]
  [1. 0. 0.]
  [1. 0. 1.]
  [1. 1. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 1.]
  [0. 1. 0.]
  [0. 1. 1.]
  [1. 0. 0.]
  [1. 0. 1.]
  [1. 1. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 1.]
  [0. 1. 0.]
  [0. 1. 1.]
  [1. 0. 0.]
  [1. 0. 1.]
  [1. 1. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 1.]
  [0. 1. 0.]
  [0. 1. 1.]
  [1. 0. 0.]
  [1. 0. 1.]
  [1. 1. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 1.]
  [0. 1. 0.]
  

In [40]:
def WriteSample(bezier, fdir, fname):
    ielems = np.array(bez.index)
    xis = np.array([p.coords for p in bez.points])
    ielems_shape = ielems.shape
    xis_shape = xis_shape
    xis = xis.flatten()
    ielems = ielems.flatten()
    file = open(fdir + "\\" + fname)
    for xi in xis:
        np.savetxt(file,)